site_name: SR RunBook
site_url: https://srobo.github.io/runbook/
repo_url: https://github.com/srobo/runbook
strict: true
edit_uri: blob/master/docs/
theme:
  logo:
    icon: library_books
  favicon: favicon.ico
  name: material
  feature:
    tabs: true
  palette:
    primary: 'blue'
    accent: 'blue'
  custom_dir: theme
copyright: |
  Copyright &copy; Student Robotics contributors
  <br>
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/" style="padding:0.2em 0.2em 0 0;float:left;height:15px;width:80px;">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" />
  </a>
  This work is licensed under a
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
    Creative Commons Attribution-ShareAlike 4.0 International License
  </a>.

# Customization
extra:
  social:
    - type: globe
      link: https://studentrobotics.org
    - type: github-alt
      link: https://github.com/srobo
    - type: twitter
      link: https://twitter.com/studentrobotics

      # Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_include:
      base_path: docs


plugins:
  - search
  - markdownextradata
